# Generated by Django 5.0.7 on 2025-03-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_payment_created_at_payment_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_request_id', models.CharField(max_length=100, unique=True)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
